android/19.02.md
=> Fixed a tag

cordova/current.md
Cordova Doc: Crash examples added, <code> tags fixes and removed extra tags (<spans>, <br> and &nbsp)
=> Cordova: Crash examples added, <code> tags fixes, removed extra tags.

react_native_bridged/current.md
- Removed extra tags (<span>, <br>)
- Replaced &nbsp with space
- Fixed <code> tag issues
- Refactor Events
- Add Github link and Minimal setup
=> RN doc changes

react_native_bridged/current.md
— Set Custom Metrics section updated.
=> — Replaced “custom event” to “event”

web/next.md
Created the next.md
Modified max_event from 10 to 100
=> next.md created with max_event changes

web/next.md
Made some changes at two places:
- First. at feature definitions where the tone of these two were less formal than other features
- Second, at a section about user reported feedback as a mention
=> [SDK-499] star-rating and feedback consent entries

web/next.md
Added some comments at two sections:
- Offline mode
- Device ID change
about automatic consent clearance at certain situations.
=> [SDK-508] Added some comments about internal consent removal

web/next.md
- Added 'Rating widget' section inside the 'Helpers'
- Modified other function calls where their names has changed
- Did not add a 'User Feedback' section yet as it belongs to another ticket
=> [SDK-545] Added rating widget

web/next.md
Added other features section with SDK internal limits.
Gave an example and listed current limits.
=> [SDK-364] Internal Limits added

web/next.md
- Added a section about manually showing rating widgets as a popup
- Added a section about showing multiple rating widgets
- Gave examples for both use cases
- Verified cohesion at scratchpad
=> [SDK-559] Added rating widget functions

web/20.11.md
Published the article
Current => 20.11.md
Next => current
=> Next to current

nodejs/next.md
- Created next.md for NodeJS
- Created new article for the old version (20.11) at zendesk's hidden section
- Referenced that url at next.md
=> [SDK-564] NodeJS new documentation

nodejs/next.md
Added a warning about consent removal during ID change without merge
=> [SDK-565] Id change consent warning

nodejs/next.md
A small segment added explaining how to toggle the logs after init.
=> [SDK-586] isloggingEnabled

cordova/current.md
Added suggested changes mentioned in ticket SDK-643.
=> [SDK-643] : Rework appkey and server url documentation.

nodejs/next.md
Node docs are not reordered, yet.
=> [SDK-642] App key info link

nodejs/next.md
Internal limits documentation entry added
=> [SDK-365] Internal limits

web/next.md
Added:
- test_mode
- rack_domains
- storage
- check_consent
- check_any_consent
- recordError
- stop_time
- start_time
=> [SDK-534] public calls

cordova/current.md, flutter/current.md, flutter/next.md, react_native_bridged/current.md
— Also apply auto formatting of file on save.
=> [SDK-714, 715, 716]— Remote Config consent fix in bridged SDK’s doc

web/next.md
in continuation to scarifying the script, added a text that links to APM section
=> [SDK-794] Clarify APM docs

unity/21.11.0.md, unity/current.md, unity/next.md
added changes in next.md
content of next.md moved in current.md.
=> 21.11.0.md created from current.md

web/next.md
https://countly.zendesk.com/knowledge/api/articles/4409195031577/translations/en-us/preview/head
=> [878] ga adapter

android/next.md, cordova/next.md, cpp/next.md, flutter/next.md, ios/next.md, java/next.md, nodejs/next.md, react_native_bridged/next.md, unity/next.md, web/next.md, windows/next.md
=> Add a link to the how to validate your countly integration web

cpp/next.md
Event -> cly::Event
Countly:: -> cly::Countly
=> [SDK 912] namespace 'cly' and C++ version updated

sdk_dev_guide/curent.md
=> fixed words

react_native_bridged/20.04.md, react_native_bridged/21.11.md, react_native_bridged/current.md, react_native_bridged/next.md
-- Android intent redirection security section added with allowed package/class names for intent redirection
=> RN doc : 22.02.0 version added

android/next.md
=> android gosswammi

cpp/next.md
answers that lay beneath the cpp
=> Goswami cpp

cpp/next.md
removed some spans and empty spaces. Added a new sdk storage h2. added some more detail how to build the sdk
=> [cpp] Adding Sqlite to project

android/next.md
Added the section and an example implementation
=> [Android] Log Listener section

android/next.md
first draft includes deprecated calls
=> [Android] Config object methods

downloading_and_installing/current.md
Links now open at new page, added links for iOS and changed some wrong links.
=> [SDK Downloading] Link behavior changes and addition

web/current.md
=> [Web] 06.5 minor release

web/next.md
added rating widget related info to feedback widgets and cleaned some code
=> [Web] User feedback changes for new API

android/next.md, flutter/next.md
=> [Android, Flutter] Package Updates and some fixes

downloading_and_installing/current.md, web/23.2.md, web/current.md, web/next.md
the current was crlf before. at some point we have to make the leap to lf. which can be now? no?
=> [Web SDK] Release Changes

cpp/current.md, java/current.md, nodejs/current.md, unity/current.md, web/current.md, windows/current.md
RN, Flutter, iOS, Android remains
=> Adding new header IDs

unity/next.md
SDK Version changed from 22.06.0 to 23.06.0
=> [Unity] SDK Version Updated

a_deeper_look_at_sdk_concepts/current.md
will publish now, feel free to merge
=> Proof reading

android/current.md, android/next.md
next includes the addsegmentation as an extra
=> [Android] Updated views

downloading_and_installing/current.md, ios/23.8.0.md, ios/next.md
-- Updated  iOS doc to 23.12.0
-- Added 'addSegmentationToViewWithID' and 'addSegmentationToViewWithName' function calls -- Added 'config.disableLocation'
-- Removed extra callouts
=> iOS Doc: Created a 23.8.0 doc file

unity/next.md
br and nbsp tags are cleaned, some lines fixed
=> [Unity] Silly tag cleanup

ios/current.md, ios/next.md
-- Added consent during init section
=> iOS Doc: Updated user consent structure

downloading_and_installing/current.md, windows/23.12.md, windows/next.md
Current windows need only publish
Downloading installing not updated in the zendesk
=> [Windows] prepare for release

sdk_dev_guide/current.md
Only some additions to the intro.
for Internal events and timed events only 'spans' are removed.
=> [Dev] Events intro revamp

flutter/current.md, flutter/next.md
I made the changes to current.md because this change is already in production.
=> [Flutter] fix user profile documentation

unity/next.md
for some reason those examples were given with 'await', further fixations will be done after user detail rework is completed, fixing the obvious issue here
=> [Unity] removed 'await' from non-awaitable methods

android/next.md, flutter/next.md, ios/next.md, java/next.md, react_native_bridged/next.md, web/next.md
Updated some sections, links, typos
=> [Multiple Docs] Added Refer to Doc Sections

react_native_bridged/current.md
diffed next and current on zendesk
=> [RN] Current Update

a_deeper_look_at_sdk_concepts/current.md, downloading_and_installing/current.md, getting_started/current.md
Will publish documents after merging
=> Documentation Header Typos

android/next.md, flutter/next.md, ios/next.md, java/next.md, nodejs/next.md, web/next.md, windows/next.md
=> [All, Doc] setID method all others

android/current.md, flutter/current.md, ios/current.md
* Deeper look
* Android
* downloading and installing
* flutter
* getting started
* ios
* sdk dev guide
docs are published
=> [All] Publish unpublished docs

sdk_dev_guide/current.md
=> [DevGuide] Server Config
